version: '3'
services:
  vue-app:
    image: nginx:latest   # 使用官方 Nginx 镜像
    container_name: vue_app
    ports:
      - "8089:80"         # 将本机的 8080 端口映射到容器的 80 端口
      - "8443:443"  # HTTPS

    volumes:
      - ./dist:/usr/share/nginx/html   # 挂载本地的 dist 目录到 Nginx 容器中的静态文件目录
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # 挂载自定义 Nginx 配置
      - ./nginx/cert:/etc/nginx/cert  # 挂载证书
    networks:
      - vue-network

networks:
  vue-network:
    driver: bridge
