// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"bookstore/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/add",
				Handler: AddHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/check",
				Handler: CheckHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: signInHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: GetUserMsgHandler(serverCtx),
			},
			// // 处理 OPTIONS 请求
			// {
			// 	Method:  http.MethodOptions,
			// 	Path:    "/user/register",
			// 	Handler: signInHandlerOption(serverCtx),
			// },
		},
	)
}
